#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5 6
# bspc monitor HDMI-0 -d 4 5 6

bspc config border_width         1
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true


# Border
bspc config focused_border_color        "#363636"
bspc config normal_border_color         "#363636"
bspc config active_border_color         "#363636"


# screen config
# xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-3 --mode 1920x1080 --rotate normal --left-of HDMI-0

# Wallpaper
${HOME}/.fehbg

# Bar
sh ~/.config/polybar_costom/launch.sh

# Trasnperacy
compton --config ~/.config/picom-or-compton/picom-or-compton.conf &
# picom only suports transperacy above v9
# picom --config ~/.config/picom-or-compton/picom-or-compton.conf

# redshift
# this comand has to be the last one
redshift -l 47.304727:-6.980062
# Notifications
#/usr/bin/dunst &

# Picom
# picom -CGb &
